### ISSUE TITLE
抢课时如果选到时间冲突的课开始抢程序就会崩溃

### ISSUE THREAD

**Issue by IcyFeather233** [PIKACHUIM/UrpHelps#1]
建议加个自动检查时间是否冲突功能，时间冲了的课不能选，出来个提示之类的

**Comment by PIKACHUIM** [comment]
倒是有这个打算，但是考虑到这个源创建于3年前，代码没有模块化，导致现在极难维护（基本无法新增内容），因此这个功能会在下次重构的时候添加（如果还有下次重构的话）

**Comment by PIKACHUIM** [comment]
0.4版本已经修复了，但是并不会提示，只是会显示在选课失败的信息里面
