### ISSUE TITLE
自动抢课功能闪退

### ISSUE THREAD

**Issue by laybxc** [PIKACHUIM/UrpHelps#2]
输入关键词后，读取教务列表时，一两秒后闪退

**Comment by laybxc** [comment]
具体可以看这个图：https://s3.bmp.ovh/imgs/2022/12/27/e6f1bb2adccd0b91.png

**Comment by PIKACHUIM** [comment]
您好，请提供下版本号呢，这个问题应该早些时候修复了，请问一下最新版本有这个问题吗

**Comment by laybxc** [comment]
我使用的是最新的版本，是不是打开方式不太对？我从release中解压的3.2然后使用的

**Comment by PIKACHUIM** [comment]
最新版本应该是0.4.0，从这里下载https://github.com/PIKACHUIM/UrpHelps/releases/download/0.4/0.4.0.rar

**Comment by laybxc** [comment]
好的，我试试，感谢学长！

**Comment by laybxc** [comment]
更新之后问题解决了，谢谢学长！
